export const FEATURES = {
  BATCH_UPLOAD_USERS: 'Phoenix_Usermanagement_Userbatch',
  SUBSIDIARIES: 'subsidiaries',
  MAINTENANCE_MODE: 'ev10_maintenance_mode',
  INITIATIVES_LABEL: 'network_filters_initiatives_activities_filter',
  IMPACT_SHARING_DOCUMENTS_SUBSIDIARY_DOCUMENT_LIST: 'impact_sharing_documents_-_subsidiary_document_list',
  IMPACT_CARBON_MODULE_EV10: 'impact_carbon_module_EV10',
  IMPACT_ANONYMIZED_USER: 'impact_anonymized_user',
  IMPACT_CARBON_CLIENT_PDF: 'impact_carbon_client_pdf',
  JEDI_ATA_DIRECTORY: 'jedi_ata_directory',
  JEDI_GROUP_HIERARCHY: 'jedi_display_group_hierarchy_in_network',
  JEDI_ANON_NETWORK: 'jedi_user_anon_network',
  JEDI_SCOPECHANGE: 'jedi_scopechange',
  JEDI_CARBON: 'jedi_carbon_dashboard',
  JEDI_ATA_MOVE_TO_NETWORK: 'jedi_ata_add_integrationIDs_when_move_to_network',
  JEDI_ATA_MOVE_TO_NETWORK_TAGS: 'jedi_ata_add_tags_when_move_to_network',
  JEDI_DIRECTORY_ONECLICK_SHARING: 'jedi_directory_oneclick_sharing',
  ANGRY_NERDS_DFS2_SEARCH_SCREEN: 'angry_nerds_DFS2_search_screen',
  ANGRY_NERDS_SHOW_MY_SUPPLIERS_ONLY: 'angry_nerds_show_my_suppliers_only',
  THUNDER_HIGH_DEMAND_INFO: 'thunder_dashboard_highDemandEvalInfo',
  NEW_CSR_EV10: 'martians_new_csr_ev10',
  THUNDER_THAI_DATES: 'thunder_thai_dashboardDeadline',
  ANGRY_NERDS_CAP_ANONYMIZATION: 'angry_nerds_cap_anonymization',
  THUNDER_PENDO_TEST_PREFIX: 'thunder_pendo_testPrefix',
  JEDI_OPTOUT_PASS_REQUESTID: 'jedi_optout_pass_requestId',
  MARTIANS_NEW_CSR_HIDE_BENCHMARK: 'martians_new_csr_ev10_HIDE_BENCHMARK',
  SPARTA_HIDE_SUBSCRIPTION_AND_BILLING: 'sparta_hide_subscription_and_billing',
  PHOENIX_DISPLAY_ELEARNING: 'phoenix_display_elearning',
  PHOENIX_TC_ONE_COMPANY: 'Phoenix_TC_OneCompany',
  THUNDER_MULTILINGUAL_MARKETING_RESOURCES: 'thunder_multilingualMarketingResources',
  ANGRY_NERDS_DFS2_SEARCH_RESULTS: 'angry_nerds_dfs_search_results',
  THUNDER_EXTENDED_WAITING_INFO: 'thunder_extendedWaitingInfo',
};

export const PROVIDERS = {
  ANAKIN: 'Anakin',
  MOCK_CLIENT: 'MockClient',
};

export const SELECTED_PROVIDER = 'ANAKIN';
